/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGráfica;

import Objetos.Venda;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SynMcall
 */
public class ControleVendas extends javax.swing.JInternalFrame {
    public static String chaveAtualizar;
    /**
     * Creates new form ControleVendas
     */
    public ControleVendas() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelaVendas.getModel();
        tabelaVendas.setRowSorter(new TableRowSorter(modelo));
        atualizarTabela();
    }
    public void atualizarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaVendas.getModel();
        modelo.setNumRows(0);
        Venda vendaF = new Venda();
        for (Iterator<Venda> it = vendaF.tabelaVendas().iterator(); it.hasNext();) {            
            Venda venda = (Venda) it.next();
            modelo.addRow(new Object[]{
                venda.getIdVenda(),
                venda.getCpfFuncionario(),                
                venda.getCpfCliente(),
                venda.getDataVenda(),
                venda.getHoraVenda(),  
                venda.getValorVenda(),
                venda.getDscArma(),   
                
            });  
        }
        } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDesk = new javax.swing.JDesktopPane();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Controle Vendas");
        setDoubleBuffered(true);
        setFocusTraversalPolicyProvider(true);

        telaDesk.setBackground(new java.awt.Color(255, 255, 255));
        telaDesk.setDoubleBuffered(true);
        telaDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                telaDeskMouseEntered(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jToggleButton2.setText("Alterar Venda");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/oie_transparent (1).png"))); // NOI18N
        jLabel5.setText("Vendas:");

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venda", "Funcionario", "Cliente", "Data Venda", "Hora Venda", "Valor", "Arma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVendas);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jButton1.setText("Cadastrar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jToggleButton1.setText("Excluir Venda");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        telaDesk.setLayer(jToggleButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaDeskLayout = new javax.swing.GroupLayout(telaDesk);
        telaDesk.setLayout(telaDeskLayout);
        telaDeskLayout.setHorizontalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        telaDeskLayout.setVerticalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(tabelaVendas.getSelectedRow() != -1){
            Venda venda = new Venda();
            venda.setIdVenda(Integer.parseInt(tabelaVendas.getValueAt(tabelaVendas.getSelectedRow(),0).toString()));
            venda.deletarVenda(venda);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastrarVenda cadastrarVenda = new CadastrarVenda();
        telaDesk.add(cadastrarVenda);
        cadastrarVenda.setVisible(true);
        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.setChaveAtualizar(tabelaVendas.getValueAt(tabelaVendas.getSelectedRow(),0).toString());        
        AlterarVenda alterarVenda = new AlterarVenda();
        telaDesk.add(alterarVenda);
        alterarVenda.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void telaDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaDeskMouseEntered
       atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_telaDeskMouseEntered

    public static String getChaveAtualizar() {
        return chaveAtualizar;
    }

    public static void setChaveAtualizar(String chaveAtualizar) {
        ControleVendas.chaveAtualizar = chaveAtualizar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JDesktopPane telaDesk;
    // End of variables declaration//GEN-END:variables
}
