/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGráfica;

import Objetos.Cargo;
import Objetos.Funcionario;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SynMcall
 */
public class ControleFuncionarios extends javax.swing.JInternalFrame {
    public static String chaveAtualizarFuncionario;
    public static String chaveAtualizarCargo;

    public static String getChaveAtualizarFuncionario() {
        return chaveAtualizarFuncionario;
    }

    public static void setChaveAtualizarFuncionario(String chaveAtualizarFuncionario) {
        ControleFuncionarios.chaveAtualizarFuncionario = chaveAtualizarFuncionario;
    }

    public static String getChaveAtualizarCargo() {
        return chaveAtualizarCargo;
    }

    public static void setChaveAtualizarCargo(String chaveAtualizarCargo) {
        ControleFuncionarios.chaveAtualizarCargo = chaveAtualizarCargo;
    }

    /**
     * Creates new form ControleFuncionarios
     */
    public ControleFuncionarios() {
        initComponents();
        initComponents();
        DefaultTableModel modeloFuncionario = (DefaultTableModel) tabelaFuncionarios.getModel();
        tabelaFuncionarios.setRowSorter(new TableRowSorter(modeloFuncionario));
        DefaultTableModel modeloCargo = (DefaultTableModel) tabelaCargos.getModel();
        tabelaCargos.setRowSorter(new TableRowSorter(modeloCargo));
        atualizarTabela();
    }
    public void atualizarTabela(){
        DefaultTableModel modeloFuncionario = (DefaultTableModel) tabelaFuncionarios.getModel();
        modeloFuncionario.setNumRows(0);
        DefaultTableModel modeloCargo = (DefaultTableModel) tabelaCargos.getModel();
        modeloCargo.setNumRows(0);
        Funcionario funcionarioF = new Funcionario();
        for (Iterator<Funcionario> it = funcionarioF.tabelaFuncionario().iterator(); it.hasNext();) {            
            Funcionario funcionario = (Funcionario) it.next();
            modeloFuncionario.addRow(new Object[]{
                funcionario.getCpf(),   
                funcionario.getNome(),                             
                funcionario.getTelefone(),
                funcionario.getEndereco(),
                funcionario.getSalarioFuncionario(),  
                funcionario.getDscCargo(),
                funcionario.getDataNascimento(),
                funcionario.getDataCadastro(),
                             
                
            });  
        }
        Cargo cargoF = new Cargo();
        for (Iterator<Cargo> it = cargoF.buscarCargos().iterator(); it.hasNext();) { 
            Cargo cargo = (Cargo) it.next();
            modeloCargo.addRow(new Object[]{
                cargo.getIdCargo(),
                cargo.getDscCargo(),
                cargo.getDscFuncoes(),
            });
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDesk = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaCargos = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Controle De Funcionarios");
        setDoubleBuffered(true);

        telaDesk.setBackground(new java.awt.Color(255, 255, 255));
        telaDesk.setAutoscrolls(true);
        telaDesk.setPreferredSize(new java.awt.Dimension(1200, 750));
        telaDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                telaDeskMouseEntered(evt);
            }
        });

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Telefone", "Endereço", "Salário", "Cargo", "Data Cadastro", "Data Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionarios);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_rh.png"))); // NOI18N
        jLabel5.setText("Funcionários:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jButton1.setText("Cadastrar Funcionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jButton2.setText("Alterar Funcionário");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jButton3.setText("Excluir Funcionário");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Despesa com Salário:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cargos.png"))); // NOI18N
        jLabel7.setText("Cargos:");

        tabelaCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cargo", "Descrição Cargo", "Descrição Funções"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaCargos);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jToggleButton1.setText("Cadastrar Cargo");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jButton4.setText("Alterar Cargo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jButton5.setText("Excluir Cargo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        telaDesk.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaDeskLayout = new javax.swing.GroupLayout(telaDesk);
        telaDesk.setLayout(telaDeskLayout);
        telaDeskLayout.setHorizontalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(telaDeskLayout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton5))
                            .addGroup(telaDeskLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(29, 29, 29)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jButton3)
                                .addGap(108, 108, 108)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaDeskLayout.setVerticalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastrarFuncionario cadastrarFuncionario = new CadastrarFuncionario();
        telaDesk.add(cadastrarFuncionario);
        cadastrarFuncionario.setVisible(true);
        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tabelaFuncionarios.getSelectedRow() != -1){
            Funcionario funcionario = new Funcionario();
            funcionario.setCpf(tabelaFuncionarios.getValueAt(tabelaFuncionarios.getSelectedRow(),0).toString());
            funcionario.deletar(funcionario);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        CadastrarCargo cadastrarCargo = new CadastrarCargo();
        telaDesk.add(cadastrarCargo);
        cadastrarCargo.setVisible(true);
        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(tabelaCargos.getSelectedRow() != -1){
            Cargo cargo = new Cargo();
            cargo.setIdCargo(Integer.parseInt(tabelaCargos.getValueAt(tabelaCargos.getSelectedRow(),0).toString()));
            cargo.deletarCargo(cargo);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setChaveAtualizarFuncionario(tabelaFuncionarios.getValueAt(tabelaFuncionarios.getSelectedRow(),0).toString());
        AlterarFuncionario alterarFuncionario = new AlterarFuncionario();
        telaDesk.add(alterarFuncionario);
        alterarFuncionario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setChaveAtualizarCargo(tabelaCargos.getValueAt(tabelaCargos.getSelectedRow(),0).toString());
        AlterarCargo alterarCargo = new AlterarCargo();
        telaDesk.add(alterarCargo);
        alterarCargo.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void telaDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaDeskMouseEntered
          atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_telaDeskMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tabelaCargos;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JDesktopPane telaDesk;
    // End of variables declaration//GEN-END:variables
}
