/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGráfica;

import Objetos.Arma;
import Objetos.Calibre;
import Objetos.Fornecedor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SynMcall
 */
public class ControleMercadoria extends javax.swing.JInternalFrame {
    public static String chaveAtualizarFornecedor;
    public static String chaveAtualizarArma;
    public static String chaveAtualizarCalibre;
    /**
     * Creates new form ControleMercadoria
     */
    public ControleMercadoria() {
        initComponents();
        DefaultTableModel modeloArmas = (DefaultTableModel) tabelaArmas.getModel();
        tabelaArmas.setRowSorter(new TableRowSorter(modeloArmas));
        DefaultTableModel modeloCalibres = (DefaultTableModel) tabelaCalibres.getModel();
        tabelaCalibres.setRowSorter(new TableRowSorter(modeloCalibres));
        DefaultTableModel modeloFornecedores = (DefaultTableModel) tabelaFornecedores.getModel();
        tabelaFornecedores.setRowSorter(new TableRowSorter(modeloFornecedores));
        atualizarTabela();
    }
    public void atualizarTabela(){
        DefaultTableModel modeloArmas = (DefaultTableModel) tabelaArmas.getModel();
        modeloArmas.setNumRows(0);
        DefaultTableModel modeloCalibres = (DefaultTableModel) tabelaCalibres.getModel();
        modeloCalibres.setNumRows(0);
        DefaultTableModel modeloFornecedores = (DefaultTableModel) tabelaFornecedores.getModel();
        modeloFornecedores.setNumRows(0);
        Arma armaF = new Arma();
        for (Arma arma : armaF.tabelaArmas()) {
            modeloArmas.addRow(new Object[]{
                arma.getIdArma(),
                arma.getDscArma(),                
                arma.getCpfFornecedor(),
                arma.getValorArma(),
                arma.getDscCalibre(),
                
  
            });
        }
        Calibre calibreF = new Calibre();
        Calibre.buscarCalibres().forEach((calibre) -> {            
            modeloCalibres.addRow(new Object[]{
                calibre.getIdCalibre(),
                calibre.getDscCalibre()
            });
        });
;
        Fornecedor fornecedorF = new Fornecedor();
        for( Fornecedor fornecedor: fornecedorF.tabelaFornecedor()){            
            modeloFornecedores.addRow(new Object[]{
                fornecedor.getIdFornecedor(),
                fornecedor.getNome(),
                fornecedor.getCpf(),                
                fornecedor.getTelefone(),
                fornecedor.getEndereco(), 
                fornecedor.getDataCadastro(),
                fornecedor.getDataNascimento(),

        });
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDesk = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaArmas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCalibres = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaFornecedores = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);

        telaDesk.setBackground(new java.awt.Color(255, 255, 255));
        telaDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                telaDeskMouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/weapon_ak_1326050.png"))); // NOI18N
        jLabel5.setText("Armas em Estoque :");

        tabelaArmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Arma", "Arma", "Fornecedor", "Valor", "Calibre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaArmas);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jButton2.setText("Cadastrar Arma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jButton3.setText("Alterar Arma");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jButton4.setText("Excluir Arma");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ammo-icon-hi.png"))); // NOI18N
        jLabel6.setText("Calibres :");

        tabelaCalibres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Calibre", "Calibre"
            }
        ));
        jScrollPane2.setViewportView(tabelaCalibres);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jButton1.setText("Cadastrar Calibre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jButton5.setText("Alterar Calibre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jButton6.setText("Excluir Calibre");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Fornecedor.png"))); // NOI18N
        jLabel7.setText("Fornecedores:");

        tabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Fornecedor", "Nome", "CPF", "Telefone", "Endereço", "Data Cadastro", "Data Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaFornecedores);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jButton7.setText("Cadastrar Fornecedor");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jButton8.setText("Alterar Fornecedor");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jButton9.setText("Excluir Fornecedor");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        telaDesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaDeskLayout = new javax.swing.GroupLayout(telaDesk);
        telaDesk.setLayout(telaDeskLayout);
        telaDeskLayout.setHorizontalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDeskLayout.createSequentialGroup()
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(61, 61, 61))
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(telaDeskLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaDeskLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaDeskLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)))
                .addGap(29, 29, 29))
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        telaDeskLayout.setVerticalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaDesk))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastrarArma cadastrarArma = new CadastrarArma();
        telaDesk.add(cadastrarArma);
        cadastrarArma.setVisible(true);
        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setChaveAtualizarArma(tabelaArmas.getValueAt(tabelaArmas.getSelectedRow(),0).toString());        
        AlterarArma alterarArma = new AlterarArma();
        telaDesk.add(alterarArma);
        alterarArma.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public static String getChaveAtualizarArma() {
        return chaveAtualizarArma;
    }

    public static void setChaveAtualizarArma(String chaveAtualizarArma) {
        ControleMercadoria.chaveAtualizarArma = chaveAtualizarArma;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(tabelaArmas.getSelectedRow() != -1){
            Arma arma = new Arma();
            arma.setIdArma(Integer.parseInt(tabelaArmas.getValueAt(tabelaArmas.getSelectedRow(),0).toString()));
            arma.deletarArma(arma);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastrarCalibre cadastrarCalibre = new CadastrarCalibre();
        telaDesk.add(cadastrarCalibre);
        cadastrarCalibre.setVisible(true);
        atualizarTabela();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(tabelaCalibres.getSelectedRow() != -1){
            Calibre calibre = new Calibre();
            calibre.setIdCalibre(Integer.parseInt(tabelaCalibres.getValueAt(tabelaCalibres.getSelectedRow(),0).toString()));
            calibre.deletarCalibre(calibre);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CadastrarFornecedor cadastrarFornecedor = new CadastrarFornecedor();
        telaDesk.add(cadastrarFornecedor);
        cadastrarFornecedor.setVisible(true);
        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(tabelaFornecedores.getSelectedRow() != -1){
            Fornecedor fornecedor = new Fornecedor();
            fornecedor.setCpf(tabelaFornecedores.getValueAt(tabelaFornecedores.getSelectedRow(),2).toString());
            fornecedor.deletar(fornecedor);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setChaveAtualizarFornecedor(tabelaFornecedores.getValueAt(tabelaFornecedores.getSelectedRow(),2).toString());        
        AlterarFornecedor alterarFornecedor = new AlterarFornecedor();
        telaDesk.add(alterarFornecedor);
        alterarFornecedor.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setChaveAtualizarCalibre(tabelaCalibres.getValueAt(tabelaCalibres.getSelectedRow(),0).toString());        
        AlterarCalibre alterarCalibre = new AlterarCalibre();
        telaDesk.add(alterarCalibre);
        alterarCalibre.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void telaDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaDeskMouseEntered

        atualizarTabela();        
    // TODO add your handling code here:
    }//GEN-LAST:event_telaDeskMouseEntered

    public static String getChaveAtualizarCalibre() {
        return chaveAtualizarCalibre;
    }

    public static void setChaveAtualizarCalibre(String chaveAtualizarCalibre) {
        ControleMercadoria.chaveAtualizarCalibre = chaveAtualizarCalibre;
    }

    public static String getChaveAtualizarFornecedor() {
        return chaveAtualizarFornecedor;
    }

    public static void setChaveAtualizarFornecedor(String chaveAtualizarFornecedor) {
        ControleMercadoria.chaveAtualizarFornecedor = chaveAtualizarFornecedor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaArmas;
    private javax.swing.JTable tabelaCalibres;
    private javax.swing.JTable tabelaFornecedores;
    private javax.swing.JDesktopPane telaDesk;
    // End of variables declaration//GEN-END:variables
}
