/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGráfica;

import Objetos.CRAF_Pessoa;
import Objetos.Cliente;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SynMcall
 */
public class ControleClientes extends javax.swing.JInternalFrame {
    public static String chaveAtualizar;
    
    /**
     * Creates new form ControleClientes
     */
    public ControleClientes() {
        initComponents();
        initComponents();
        DefaultTableModel modeloCliente = (DefaultTableModel) tabelaCliente.getModel();
        tabelaCliente.setRowSorter(new TableRowSorter(modeloCliente));
        DefaultTableModel modeloCRAF = (DefaultTableModel) tabelaCRAF.getModel();
        tabelaCRAF.setRowSorter(new TableRowSorter(modeloCRAF));
        atualizarTabela();
    }
    public void atualizarTabela(){
        DefaultTableModel modeloCliente = (DefaultTableModel) tabelaCliente.getModel();
        modeloCliente.setNumRows(0);
        DefaultTableModel modeloCRAF = (DefaultTableModel) tabelaCRAF.getModel();
        modeloCRAF.setNumRows(0);
        Cliente clienteF = new Cliente();
        for (Iterator<Cliente> it = clienteF.tabelaCliente().iterator(); it.hasNext();) {            
            Cliente cliente = (Cliente) it.next();
            modeloCliente.addRow(new Object[]{                
                cliente.getCpf(),
                cliente.getNome(),                
                cliente.getTelefone(),
                cliente.getEndereco(), 
                cliente.getDataCadastro(),
                cliente.getDataNascimento(),
                cliente.getRegistroCRAF(), 
            });  
        }
        CRAF_Pessoa crafF = new CRAF_Pessoa();
        for(CRAF_Pessoa craf: crafF.buscarCRAF() ){
            modeloCRAF.addRow(new Object[]{ 
                craf.getRegistroCRAF(),
                craf.getDataExpedição(),
                craf.getDataValidade(),
                craf.getOrgãoExpedidor(),
            });
        }
        }

    public static String getChaveAtualizar() {
        return chaveAtualizar;
    }

    public static void setChaveAtualizar(String chaveAtualizar) {
        ControleClientes.chaveAtualizar = chaveAtualizar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDesk = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCRAF = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Controle Clientes");

        telaDesk.setBackground(new java.awt.Color(255, 255, 255));
        telaDesk.setDoubleBuffered(true);
        telaDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                telaDeskMouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/oie_transparent.png"))); // NOI18N
        jLabel5.setText("Clientes:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/excluir.png"))); // NOI18N
        jButton3.setText("Excluir Cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Telefone", "Endereço", "Data Cadastro", "Data Nascimento", "CRAF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        jButton1.setText("Cadastrar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jButton2.setText("Alterar Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CRAF.png"))); // NOI18N
        jLabel6.setText("Registros CRAF:");

        tabelaCRAF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro CRAF", "Data Expedição", "Data Vencimento", "Orgão Expedidor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaCRAF);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar.png"))); // NOI18N
        jToggleButton1.setText("Alterar CRAF");

        telaDesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        telaDesk.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaDeskLayout = new javax.swing.GroupLayout(telaDesk);
        telaDesk.setLayout(telaDeskLayout);
        telaDeskLayout.setHorizontalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(telaDeskLayout.createSequentialGroup()
                        .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(telaDeskLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton1))
                            .addGroup(telaDeskLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)
                                .addGap(29, 29, 29)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        telaDeskLayout.setVerticalGroup(
            telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaDesk)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tabelaCliente.getSelectedRow() != -1){
            Cliente cliente = new Cliente();
            cliente.setCpf(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(),0).toString());
            cliente.deletar(cliente);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastrarCliente cadastraCliente = new CadastrarCliente();
        telaDesk.add(cadastraCliente);
        cadastraCliente.setVisible(true);
        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setChaveAtualizar(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(),0).toString());
        AlterarCliente alterarCliente = new AlterarCliente();
        telaDesk.add(alterarCliente);
        alterarCliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void telaDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaDeskMouseEntered
          atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_telaDeskMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tabelaCRAF;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JDesktopPane telaDesk;
    // End of variables declaration//GEN-END:variables
}
